name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build binary
        run: |
          docker buildx build --build-arg NGX_VERSION=1.23.3 -t ngx-basic-auth-decode .
          docker_id=$(docker create --rm ngx-basic-auth-decode)
          docker cp $docker_id:/etc/nginx/modules/libngx_basic_auth_decode.so ./
          docker stop $docker_id
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{steps.version.output.version}}
          tag_name: ${{github.sha}}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{github.token}}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./libngx_basic_auth_decode.so
          asset_name: libngx_basic_auth_decode.so
          # asset_content_type: application/binary
